sudo: required

services:
  - docker

env:
  global:
    - secure: "iz3ZSA62tVDeMQnzJwLTATSik7QqYEgbRfxhETgeNvDVGad7jD089MMhGpYAonT6anQlGxa9SlIfHPppvXPoY6SmVzXYHOeSb7Yrsr/MSJiYSfXDWuwzHYs68sRESx421/TgioH/g/ka0aQ2+7Oy8kLgbR6j2EaDAA2G+CzmzkeSiQnTfU+W4i2KofjT94oQIhvj4Br6wYmVCaPUSjDgpgbXsqW3y05EGpzALQyTbaXq/UrSp0moojDzpB0Py/DH/8vbv14IA+SgdQmHhoYebXdyDjBDbCTegYKbmLVqv7rPZvR5QbnmSh6ozPHSRuoeZzfHDGIiOVYKiBQsYH/obn+KTeNumo+wTX72SbS1YijoQizpHa1WCw4AdP+oK4+MqZGAVUMpcjwAx8p7etpfgdk4ArBMwaGOJhZ23DFR+xl351lCmHlqb1FMytv98fM6EVW5BlIL3kLMCgnZMEbQMj84w9vNR0FRoVz8GmKTDQsvshGRV1Y4VabBIwqA+8Yr70ZVbH4kAlC/2HSqyGPctQVIF5WAIbaEnnPpdY9G/rwl8iGGYRHCDVyJnM8y7F79dJem/Oj0IsyCsGzX5x462B8VehdmOrl2iFqcCmTAV83MwPxSYyHCuHQzeJHGqLjI5lDE7bmM7TIUWoCqUSA6kGsRSFaVLjaS3XSr/kUiSOI=" # DOCKER_USER
    - secure: "n1GS8d53K8NIy1xsdEk65nz77rUuUroCMmqJWRzrZQ66CXefbr2lOq1GJ4VIXBGcfNJpNfIN0Ue6HvUeeBPjCoQnRELTSalTiGyH34/JMGND126vAxgiSaZPneHOJTg3TSKW0wLYIILtWt4b2bYekb8GAZHnyO+6eW0ZabiCDgQld0uxSCUn5s62R9N/AVhP286k+h4plsr6/+G2p/kGR7H+MBjBlaiGf3hSYt/BkQ38TQSOkcFD0mb+OEXEYkMIJJlrI4MgIOu/H7sc/VtAyyfGa5gXQCGKpBJRAA8pY6KVfnEnlmTFRA0/oNB0Cui4wJ+vBbWbGANlxBIC5OI2k4pADYDL+2nedfBYrOme8cZubYkPP0ApnR8y382bwnSWN2Ji3PWoa3iyI/RFkWjGQVv1DfVkD0BgfC20lpaex2Pq5/TO7NII78/ZZKDCKy8SFQZKJZ3ZUcb8bFQcR9biVng/A3LfEOwaLK89ubInK0++OSlObjH+bgBpRj42asGJtZ2BDjoIyW3dN05jjRUFIYNs6MZhw3tfdh/2TeNPqpRuq9/DxWicYrmDoAFiLuuSqHLdscPAe7IDzCr6fBHLIAJMSzA8No01JAz7f590ZNShgIC85Gw+tBQXkVS3/wrvHAf0b3uuBKwQVU5XVWMDB9BAUo3QM7FOVggi8eiICo4=" # DOCKER_PASS
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=joengenduvel/development-machine

before_script:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  
script:
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
